services:
  - type: web
    name: trxtogpt-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: MERCHANT_ADDRESS
        value: TX8m2tzReoVU4v85A38p1YkGf1ggp2BgU3
      - key: TRONGRID_API_KEY
        value: 5524121e-1050-48b8-a0a6-2b046b271d85
      - key: FRONTEND_URL
        sync: false
      - key: DB_HOST
        fromDatabase:
          name: trxtogpt-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: trxtogpt-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: trxtogpt-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: trxtogpt-db
          property: password
      - key: DATABASE_URL
        fromDatabase:
          name: trxtogpt-db
          property: connectionString

  - type: worker
    name: trxtogpt-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python payment_checker.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: MERCHANT_ADDRESS
        value: TX8m2tzReoVU4v85A38p1YkGf1ggp2BgU3
      - key: TRONGRID_API_KEY
        value: 5524121e-1050-48b8-a0a6-2b046b271d85
      - key: DB_HOST
        fromDatabase:
          name: trxtogpt-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: trxtogpt-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: trxtogpt-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: trxtogpt-db
          property: password
      - key: DATABASE_URL
        fromDatabase:
          name: trxtogpt-db
          property: connectionString

  - type: web
    name: trxtogpt-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: NODE_VERSION
        value: 16.15.0
      - key: REACT_APP_API_URL
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: trxtogpt-db
    databaseName: trxtogpt
    user: trxtogpt 